
meta_product_name: "Reko"
meta_title: "Reko - Friends know best."
meta_description: "Get and give recommendations from your close friends."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
